# Generated by Django 4.2.2 on 2023-07-30 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppConfigs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='AppID',
        ),
        migrations.AddField(
            model_name='app',
            name='AppID',
            field=models.CharField(default='PULL', max_length=100),
        ),
        migrations.AddField(
            model_name='app',
            name='Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppConfigs.category'),
        ),
    ]
