# Generated by Django 4.2.2 on 2023-07-30 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppConfigs', '0002_remove_category_appid_app_appid_app_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, default='NP', max_length=100),
        ),
    ]
