# Generated by Django 4.2.2 on 2023-07-31 23:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppConfigs', '0003_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='Type',
        ),
        migrations.AddField(
            model_name='category',
            name='ResponseData',
            field=models.TextField(default='Response'),
        ),
        migrations.AddField(
            model_name='category',
            name='UdatedTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
