version: '3.4'

# services:
#   djangofastapi:
#     image: djangofastapi
#     build:
#       context: .
#       dockerfile: ./Dockerfile
#     ports:
#       - :8000


# Build a multiservice arhitecture.
services:
  # Create a service called web
  web:
    # Build an image from the files in the project root directory (Dockerfile)
    build: .
    # Assigns a name for the container. If no name is specified,
    # Docker will assign the container a random name
    container_name: django-web
    # Mount the container `/drf` folder to the a `src` folder in the location
    # of the Dockerfile on the host machine.
    volumes:
      - ./src:/drf
    # Map port 8000 to port 9090 so that we can access the application on
    # our host machine by visiting 127.0.0.1:9090
    ports:
      - "9090:8000"